version: "3.9"

services:
  web:
    build: .
    restart: unless-stopped
    container_name: task
    networks:
      - caddy
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

networks:
    caddy:
        external: true